
  name: eos-voter
  version: '0.3.0'
  summary: Light wallet and producer voting tool for EOS
  description: |
    eos-voter is a limited-functionality release of a light wallet 
    being designed for the EOS blockchain. This application can be used 
    to connect to a remote EOS API endpoint to perform producer voting 
    actions and a few basic wallet commands.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      plugin: nil
  
